config/routes.rb
Rails.application.routes.draw do
  get 'vigenere_encode/index'

  get 'vigenere_encode/new'

  post 'vigenere_encode/show'
  get 'vigenere_encode/show'

  get 'decoding/index'

  get 'decoding/new'

  post 'decoding/show'
  get 'decoding/show'

  get 'encodings/index'

  get 'encodings/new'

  post 'encodings/show'
  get 'encodings/show'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/decoding_controller.rb
class DecodingController < ApplicationController
  skip_before_filter :verify_authenticity_token
  #Shouldn't have to do this with database work - just doing this for right now

  def index
  end

  def new
  end

  def show
    @message = Caesar.decode(params[:shift], params[:message])
  end
end

app/controllers/encodings_controller.rb
class EncodingsController < ApplicationController
  skip_before_filter :verify_authenticity_token
  #Shouldn't have to do this with database work - just doing this for right now


  def index
  end

  def new
  end

  def show
    # From our form - we get a hash =====> params= {'message' => 'hello world', 'shift' => 's'}
    @message = Caesar.encode(params[:shift], params[:message])
  end
end

app/controllers/vigenere_encode_controller.rb
class VigenereEncodeController < ApplicationController
  skip_before_filter :verify_authenticity_token
  #Shouldn't have to do this with database work - just doing this for right now


  def index
  end

  def new
  end

  def show
    @message = Vigenere.encode(params[:shift], params[:message])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/decoding_helper.rb
module DecodingHelper
end

app/helpers/encodings_helper.rb
module EncodingsHelper
end

app/helpers/vigenere_encode_helper.rb
module VigenereEncodeHelper
end

app/views/decoding/index.html.erb
<h1>Decodings#index</h1>
<p><%= link_to "Decode a message", decoding_new_path %></p>

app/views/decoding/new.html.erb
<h1>Decoding a Message!</h1>

<form action="show" method="post" charset="utf-8">
  <label for="shift"> Offset Letter: </label>
  <input type="text" name="shift" id="shift" />

  <label for="message"> Your Message: </label>
  <input type="text" name="message" id="message" />

  <input type="submit" value="Decode!"/>
</form>

app/views/decoding/show.html.erb
<h1>Here's your decoded message! </h1>
<p><%= @message %></p>

app/views/encodings/index.html.erb
<h1>Encodings#index</h1>
<p><%= link_to "Encode a message", encodings_new_path %></p>

app/views/encodings/new.html.erb
<h1>Encoding a Message! </h1>

<form action="show" method="post" accept-charset="utf-8">
  <label for="shift"> Offset Letter: </label>
  <input type="text" name="shift" id="shift" />   <%# name is how you access it in params field %>

  <label for="message"> Your Message: </label>
  <input type="text" name="message" id="message" />

  <input type=submit value="Encode!" />
  <%# The type="submit" is what makes it look like a button %>
</form>

app/views/encodings/show.html.erb
<h1> Here's your encoded message: </h1>
<p><%= @message %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CaesarCipher</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/vigenere_encode/index.html.erb
<h1>VigenereEncode#index</h1>
<p>
  <%= link_to "Encoding a message with Vigenere Encoding", vigenere_encode_new_path %>
</p>

app/views/vigenere_encode/new.html.erb
<h1>Encode a Message with Vigenere</h1>

<form action="show" method="post" accept-charset="utf-8">
  <label for="shift"> Offset Letters (give three!): </label>
  <input type="text" name="shift" id="shift" />   <%# name is how you access it in params field %>

  <label for="message"> Your Message: </label>
  <input type="text" name="message" id="message" />

  <input type=submit value="Encode!" />
  <%# The type="submit" is what makes it look like a button %>
</form>

app/views/vigenere_encode/show.html.erb
<h1>Here's Your Vigenere Encoded Message</h1>
<p><%= @message %></p>